### ISSUE TITLE
Inheritance for Post (or any) Meta

### ISSUE THREAD

**Issue by misiman** [helsingborg-stad/wp-content-translator#1]
Hi, I have a question regarding meta inheritance.

In wp-content-translator/comment/connections, I see you have added comment inheritance. Is it possible to use this principle for untranslated meta? For example:

- A post is created in EN and has some metadata attached in EN
- Subsequently, the post is translated into DE (but not the metadata which remains only in EN)
- The post is viewed in DE and, as the metadata is not translated, the EN data is displayed

Thanks

**Comment by sebastianthulin** [comment]
Yes, this should be the default behaviour on all translatable meta. Have a look at the function at row 178 here: https://github.com/helsingborg-stad/wp-content-translator/blob/master/source/php/Translate/Meta.php#178.

**Comment by misiman** [comment]
Thanks, I'll give it a try.
